/-
Copyright (c) 2026 Justus Springer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Anouk Brose, Mei Han, Jesus de Loera, Justus Springer, Santiago Morales, ...
-/

import Polyhedral.Mathlib.Geometry.Convex.Cone.Pointed.Basic
import Polyhedral.Mathlib.Algebra.Module.Lattice.Basic
import Mathlib.Algebra.Order.Floor.Ring
import Mathlib.Algebra.EuclideanDomain.Int
import Mathlib.Data.Int.Interval

/-!
# Gordan's lemma

For a lattice `Λ` in a `K`-vector space `V` and a finite family `r : ι → Λ`, the monoid of lattice
points of the cone spanned by `r` is generated by `r` together with the lattice points of the
half-open parallelepiped spanned by `r`. If `r` is `K`-linearly independent, the decomposition is
unique.

-/

variable (K : Type*) [Field K] [LinearOrder K] [IsStrictOrderedRing K] [FloorRing K]
variable {V : Type*} [AddCommGroup V] [Module K V]

/-- The monoid of lattice points of a pointed cone in a lattice. -/
abbrev PointedCone.latticePoints (C : PointedCone K V) (Λ : Submodule ℤ V) : AddSubmonoid V :=
  C.toAddSubmonoid ⊓ Λ.toAddSubmonoid

namespace Gordan

open Module

variable {ι : Type*} [Fintype ι]
variable (Λ : Submodule ℤ V) (r : ι → Λ)

/-- The cone spanned by the lattice vectors `r`. -/
abbrev cone : PointedCone K V := PointedCone.hull K (Set.range (Subtype.val ∘ r))

/-- The half-open parallelepiped spanned by the rays `r`. -/
def parallelepiped : Set V :=
  { x | ∃ μ : ι → K, (∀ i, μ i ∈ Set.Ico (0 : K) 1) ∧ x = ∑ i, μ i • (r i : V) }

omit [IsStrictOrderedRing K] [FloorRing K] in
lemma mem_parallelepiped_iff {x : V} :
    x ∈ parallelepiped K Λ r ↔
      ∃ μ : ι → K, (∀ i, μ i ∈ Set.Ico (0 : K) 1) ∧ x = ∑ i, μ i • (r i : V) :=
  Iff.rfl

omit [FloorRing K] in
lemma parallelepiped_subset_cone : parallelepiped K Λ r ⊆ (cone K Λ r : Set V) := by
  rintro x ⟨μ, hμ, rfl⟩
  refine Submodule.sum_mem _ fun i _ ↦ ?_
  have h : μ i • (r i : V) = (⟨μ i, (hμ i).1⟩ : {c : K // 0 ≤ c}) • (r i : V) := rfl
  rw [h]
  exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨i, rfl⟩)

/-- Finiteness of the parallelepiped intersected with the lattice. -/
theorem parallelepiped_inter_lattice_finite [Λ.IsLattice' K] :
    (parallelepiped K Λ r ∩ (Λ : Set V)).Finite := by
  obtain ⟨I, v, hv⟩ := Submodule.IsLattice'.exists_basis_linearIndependent K Λ
  have : Finite I := Module.Finite.finite_basis v
  have := Fintype.ofFinite I
  let a i j := v.repr (r i) j
  let box : Set V := (fun c ↦ ∑ j, c j • v j) ''
      {c : I → ℤ | ∀ j, c j ∈ Set.Icc (-∑ i, |a i j|) (∑ i, |a i j|)}
  apply Set.Finite.subset (s := box)
  · exact ((Set.Finite.pi' fun j ↦ Set.finite_Icc _ _).image _)
  rintro x ⟨⟨μ, hμ, hx⟩, hxΛ⟩
  let c (i : I) := v.repr ⟨x, hxΛ⟩ i
  have hc : x = ∑ j, (c j : K) • (v j).1 := by
    have := congr($(v.sum_repr ⟨x, hxΛ⟩).1).symm
    dsimp at this
    rw [this]
    push_cast
    congr
    ext i
    rw [Int.cast_smul_eq_zsmul]
  have hr (i : ι) : r i = ∑ j, a i j • (v j).1 := by
    rw [← v.sum_repr (r i)]
    push_cast
    rfl
  have hcoord : ∀ j, c j = ∑ i, μ i * a i j :=
    Fintype.linearIndependent_iffₛ.mp hv _ _ <| by
      rw [← hc]
      rw [hx]
      rw [Fintype.sum_congr _ _ (fun _ ↦ by rw [hr])]
      simp_rw [Finset.smul_sum, Finset.sum_smul]
      rw [Finset.sum_comm]
      simp_rw [← zsmul_eq_mul', smul_assoc]
      congr
      ext i
      congr
      ext j
      apply smul_comm
  refine ⟨c, ⟨fun j ↦ abs_le.mp ?_, ?_⟩⟩
  · rw [← Int.cast_le (R := K)]
    rw [Int.cast_abs, hcoord]
    grw [Finset.abs_sum_le_sum_abs]
    simp_rw [abs_mul]
    push_cast
    apply Finset.sum_le_sum
    intro i _
    apply mul_le_of_le_one_left
    · exact abs_nonneg _
    · rw [abs_eq_self.mpr (hμ i).1]
      exact (hμ i).2.le
  conv at hc =>
    rhs
    enter [2]
    ext j
    rw [Int.cast_smul_eq_zsmul]
  exact hc.symm

-- useful lemmas:
#check Int.self_sub_floor
#check Int.floor_add_fract
#check Int.fract_nonneg
#check Int.fract_lt_one
#check Int.cast_smul_eq_zsmul
#check natCast_zsmul

/-- Every lattice point of the cone is the sum of a lattice point of the half-open parallelepiped
and an `ℕ`-combination of the rays. Split the coefficients into integer and fractional parts. -/
theorem exists_decomp (γ : V) (hγ : γ ∈ (cone K Λ r).latticePoints K Λ) :
    ∃ pn : ↥(parallelepiped K Λ r ∩ (Λ : Set V)) × (ι → ℕ),
      γ = (pn.1 : V) + ∑ i, pn.2 i • (r i : V) := by
  obtain ⟨c, hc⟩ := (Submodule.mem_span_range_iff_exists_fun _).mp hγ.1
  -- split γ into integral and fractional parts
  sorry

/-- Uniqueness of `Gordan.exists_decomp`. Needs `K`-linear independence of the rays. -/
theorem decomp_unique (hr : LinearIndependent K (Subtype.val ∘ r))
    {pn qm : ↥(parallelepiped K Λ r ∩ (Λ : Set V)) × (ι → ℕ)}
    (h : (pn.1 : V) + ∑ i, pn.2 i • (r i : V) = (qm.1 : V) + ∑ i, qm.2 i • (r i : V)) :
    pn = qm := sorry

/-- `Gordan.exists_decomp` and `Gordan.decomp_unique` combined. -/
theorem existsUnique_decomp (hr : LinearIndependent K (Subtype.val ∘ r)) (γ : V)
    (hγ : γ ∈ (cone K Λ r).latticePoints K Λ) :
    ∃! pn : ↥(parallelepiped K Λ r ∩ (Λ : Set V)) × (ι → ℕ),
      γ = (pn.1 : V) + ∑ i, pn.2 i • (r i : V) := by
  obtain ⟨pn, hpn⟩ := exists_decomp K Λ r γ hγ
  exact ⟨pn, hpn, fun _ hqm ↦ decomp_unique K Λ r hr (hqm.symm.trans hpn)⟩

omit [FloorRing K] in
/-- A decomposition is a lattice point of the cone. -/
lemma decomp_mem (pn : ↥(parallelepiped K Λ r ∩ (Λ : Set V)) × (ι → ℕ)) :
    (pn.1 : V) + ∑ i, pn.2 i • (r i : V) ∈ (cone K Λ r).latticePoints K Λ := by
  have hc : ∀ i, (r i : V) ∈ cone K Λ r := fun i ↦ Submodule.subset_span ⟨i, rfl⟩
  exact ⟨add_mem (parallelepiped_subset_cone K Λ r pn.1.2.1)
      (Submodule.sum_mem _ fun i _ ↦ nsmul_mem (hc i) _),
    add_mem pn.1.2.2 (Submodule.sum_mem _ fun i _ ↦ nsmul_mem (r i).2 _)⟩

/-- `Gordan.existsUnique_decomp`, packaged as a bijection. -/
noncomputable def decompEquiv (hr : LinearIndependent K (Subtype.val ∘ r)) :
    (↥(parallelepiped K Λ r ∩ (Λ : Set V)) × (ι → ℕ)) ≃ ↥((cone K Λ r).latticePoints K Λ) :=
  Equiv.ofBijective (fun pn ↦ ⟨_, decomp_mem K Λ r pn⟩)
    ⟨fun _ _ h ↦ decomp_unique K Λ r hr (congrArg Subtype.val h),
      fun γ ↦ (exists_decomp K Λ r γ γ.2).imp fun _ h ↦ Subtype.ext h.symm⟩

/-- The proposed set of generators. -/
def generators : Set V :=
  (parallelepiped K Λ r ∩ (Λ : Set V)) ∪ Set.range (Subtype.val ∘ r)

theorem generators_finite [Λ.IsLattice' K] : (generators K Λ r).Finite :=
  (parallelepiped_inter_lattice_finite K Λ r).union (Set.finite_range _)

/-- **Gordan's lemma**: the monoid of lattice points of the cone is generated by
`Gordan.generators`. -/
theorem gordan :
    AddSubmonoid.closure (generators K Λ r) = (cone K Λ r).latticePoints K Λ := by
  -- AI slop, need to understand and refactor
  refine le_antisymm (AddSubmonoid.closure_le.mpr ?_) fun γ hγ ↦ ?_
  · rintro x (⟨hxP, hxΛ⟩ | ⟨i, rfl⟩)
    · exact ⟨parallelepiped_subset_cone K Λ r hxP, hxΛ⟩
    · exact ⟨Submodule.subset_span ⟨i, rfl⟩, (r i).2⟩
  · obtain ⟨⟨p, n⟩, hpn⟩ := exists_decomp K Λ r γ hγ
    rw [hpn]
    refine add_mem (AddSubmonoid.subset_closure (Set.mem_union_left _ p.2))
      (AddSubmonoid.sum_mem _ fun i _ ↦ ?_)
    have hri : (r i : V) ∈ generators K Λ r := Or.inr ⟨i, rfl⟩
    exact nsmul_mem (AddSubmonoid.subset_closure hri) _

/-- **Gordan's lemma**, classical form: the monoid of lattice points is finitely generated. -/
theorem latticePoints_fg {ι : Type*} [Finite ι] (Λ : Submodule ℤ V) (r : ι → Λ)
    [Λ.IsLattice' K] : ((cone K Λ r).latticePoints K Λ).FG := by
  cases nonempty_fintype ι
  exact ⟨(generators_finite K Λ r).toFinset, by
    rw [Set.Finite.coe_toFinset]; exact gordan K Λ r⟩

end Gordan
