/-
Copyright (c) 2026 Justus Springer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Anouk Brose, Mei Han, Jesus de Loera, Justus Springer, Santiago Morales, ...
-/

import Polyhedral.Mathlib.Geometry.Convex.Cone.Pointed.Basic
import Polyhedral.Mathlib.Algebra.Module.Lattice.Basic
import Mathlib.Algebra.Order.Floor.Ring
import Mathlib.Algebra.EuclideanDomain.Int
import Mathlib.Data.Int.Interval

/-!
# Gordan's lemma

For a lattice `Λ` in a `K`-vector space `V` and a finite family `r : ι → Λ`, the monoid of lattice
points of the cone spanned by `r` is generated by `r` together with the lattice points of the
half-open parallelepiped spanned by `r`. If `r` is `K`-linearly independent, the decomposition is
unique.

-/

variable (K : Type*) [Field K] [LinearOrder K] [IsStrictOrderedRing K] [FloorRing K]
variable {V : Type*} [AddCommGroup V] [Module K V]

/-- The monoid of lattice points of a pointed cone in a lattice. -/
abbrev PointedCone.latticePoints (C : PointedCone K V) (Λ : Submodule ℤ V) : AddSubmonoid V :=
  C.toAddSubmonoid ⊓ Λ.toAddSubmonoid

namespace Gordan

open Module

variable {ι : Type*} [Fintype ι]
variable (Λ : Submodule ℤ V) (r : ι → Λ)

/-- The cone spanned by the lattice vectors `r`. -/
abbrev cone : PointedCone K V := PointedCone.hull K (Set.range (Subtype.val ∘ r))

/-- The half-open parallelepiped spanned by the rays `r`. -/
def parallelepiped : Set V :=
  { x | ∃ μ : ι → K, (∀ i, μ i ∈ Set.Ico (0 : K) 1) ∧ x = ∑ i, μ i • (r i : V) }

omit [IsStrictOrderedRing K] [FloorRing K] in
lemma mem_parallelepiped_iff {x : V} :
    x ∈ parallelepiped K Λ r ↔
      ∃ μ : ι → K, (∀ i, μ i ∈ Set.Ico (0 : K) 1) ∧ x = ∑ i, μ i • (r i : V) :=
  Iff.rfl

omit [FloorRing K] in
lemma parallelepiped_subset_cone : parallelepiped K Λ r ⊆ (cone K Λ r : Set V) := by
  rintro x ⟨μ, hμ, rfl⟩
  refine Submodule.sum_mem _ fun i _ ↦ ?_
  have h : μ i • (r i : V) = (⟨μ i, (hμ i).1⟩ : {c : K // 0 ≤ c}) • (r i : V) := rfl
  rw [h]
  exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨i, rfl⟩)

omit [LinearOrder K] [IsStrictOrderedRing K] [FloorRing K] in
/-- A vector of the lattice `Λ` is the `K`-linear combination of a `ℤ`-basis `b` of `Λ` whose
coefficients are the (integer) `b`-coordinates of the vector. -/
lemma coe_eq_sum_repr {I : Type*} [Fintype I] (b : Basis I ℤ Λ) (x : Λ) :
    (x : V) = ∑ j, ((b.repr x j : ℤ) : K) • (b j : V) := by
  simp only [Int.cast_smul_eq_zsmul]
  conv_lhs => rw [← b.sum_repr x]
  push_cast
  rfl

omit [LinearOrder K] [IsStrictOrderedRing K] [FloorRing K] in
/-- Step 3b (expansion). Substituting `r i = ∑ j, a i j • v j` and swapping the two sums turns a
`K`-combination of the rays into a `K`-combination of the basis vectors. -/
lemma sum_smul_rays_eq {I : Type*} [Fintype I] (v : I → V) (a : ι → I → ℤ) (μ : ι → K)
    (hr : ∀ i, (r i : V) = ∑ j, ((a i j : ℤ) : K) • v j) :
    ∑ i, μ i • (r i : V) = ∑ j, (∑ i, μ i * ((a i j : ℤ) : K)) • v j := sorry

omit [FloorRing K] in
/-- Step 3c (the bound). If an integer `n` is a combination `∑ i, μ i * a i` of integers `a i` with
coefficients `μ i ∈ [0, 1)`, then `|n| ≤ ∑ i, |a i|`. -/
lemma abs_le_sum_abs_of_mem_Ico {n : ℤ} {a : ι → ℤ} {μ : ι → K}
    (hμ : ∀ i, μ i ∈ Set.Ico (0 : K) 1) (h : (n : K) = ∑ i, μ i * ((a i : ℤ) : K)) :
    |n| ≤ ∑ i, |a i| := sorry

omit [FloorRing K] in
/-- **Step 3.** Suppose the vectors `v` are `K`-linearly independent, every lattice point is an
integer combination of them, and the rays expand as `r i = ∑ j, a i j • v j`. Then every lattice
point of the half-open parallelepiped has integer `v`-coordinates bounded by `B j = ∑ i, |a i j|`,
i.e. `P ∩ Λ` is contained in the image of the integer box `∏ j, [-B j, B j]` under
`c ↦ ∑ j, c j • v j`.

The three ingredients are: expanding the rays (`Gordan.sum_smul_rays_eq`), comparing the two
`v`-expansions of a point via `K`-linear independence, and the bound coming from `0 ≤ μ i < 1`
(`Gordan.abs_le_sum_abs_of_mem_Ico`). -/
lemma parallelepiped_inter_lattice_subset_box {I : Type*} [Fintype I] (v : I → V)
    (hv : LinearIndependent K v)
    (hΛ : ∀ x ∈ Λ, ∃ c : I → ℤ, x = ∑ j, (c j : K) • v j)
    (a : ι → I → ℤ) (hr : ∀ i, (r i : V) = ∑ j, (a i j : K) • v j) :
    parallelepiped K Λ r ∩ (Λ : Set V) ⊆
      (fun c : I → ℤ ↦ ∑ j, (c j : K) • v j) ''
        {c : I → ℤ | ∀ j, c j ∈ Set.Icc (-∑ i, |a i j|) (∑ i, |a i j|)} := by
  rintro x ⟨⟨μ, hμ, rfl⟩, hxΛ⟩
  obtain ⟨c, hc⟩ := hΛ _ hxΛ
  have hcoord : ∀ j, (c j : K) = ∑ i, μ i * (a i j : K) :=
    Fintype.linearIndependent_iffₛ.mp hv _ _ <| by
      rw [← sum_smul_rays_eq K Λ r v a μ hr, ← hc]
  exact ⟨c, ⟨fun j ↦ abs_le.mp (abs_le_sum_abs_of_mem_Ico K hμ (hcoord j)), hc.symm⟩⟩

/-- The hard part: finiteness of the parallelepiped intersected with the lattice.

Informal proof. Choose a `ℤ`-basis `v` of `Λ`; it is `K`-linearly independent, so `Λ`-membership
is the same as having integer coordinates w.r.t. `v`, and those coordinates are unique even over
`K`. Write each ray as `r i = ∑ j, a i j • v j` with `a i j : ℤ`. A point of the parallelepiped is
`x = ∑ i, μ i • r i = ∑ j (∑ i, μ i * a i j) • v j` with `0 ≤ μ i < 1`; if moreover `x ∈ Λ`, then
its coordinates `c j` are integers, and comparing the two `v`-expansions of `x` gives
`c j = ∑ i, μ i * a i j`, whence `|c j| ≤ ∑ i, |a i j| =: B j`. So `P ∩ Λ` is contained in the
image of the finite box of integer vectors `|c j| ≤ B j`. -/
theorem parallelepiped_inter_lattice_finite [Λ.IsLattice' K] :
    (parallelepiped K Λ r ∩ (Λ : Set V)).Finite := by
  obtain ⟨I, b, hbK⟩ := Submodule.IsLattice'.exists_basis_linearIndependent K Λ
  have : Finite I := Module.Finite.finite_basis b
  have := Fintype.ofFinite I
  have key := parallelepiped_inter_lattice_subset_box K Λ r (fun j ↦ (b j : V)) hbK
    (fun x hx ↦ ⟨fun j ↦ b.repr ⟨x, hx⟩ j, coe_eq_sum_repr K Λ b ⟨x, hx⟩⟩)
    (fun i j ↦ b.repr (r i) j) (fun i ↦ coe_eq_sum_repr K Λ b (r i))
  exact ((Set.Finite.pi' fun j ↦ Set.finite_Icc _ _).image _).subset key

-- useful lemmas:
#check Int.self_sub_floor
#check Int.floor_add_fract
#check Int.fract_nonneg
#check Int.fract_lt_one
#check Int.cast_smul_eq_zsmul
#check natCast_zsmul

/-- Every lattice point of the cone is the sum of a lattice point of the half-open parallelepiped
and an `ℕ`-combination of the rays. Split the coefficients into integer and fractional parts. -/
theorem exists_decomp (γ : V) (hγ : γ ∈ (cone K Λ r).latticePoints K Λ) :
    ∃ pn : ↥(parallelepiped K Λ r ∩ (Λ : Set V)) × (ι → ℕ),
      γ = (pn.1 : V) + ∑ i, pn.2 i • (r i : V) := by
  obtain ⟨c, hc⟩ := (Submodule.mem_span_range_iff_exists_fun _).mp hγ.1
  -- split γ into integral and fractional parts
  sorry

/-- Uniqueness of `Gordan.exists_decomp`. Needs `K`-linear independence of the rays. -/
theorem decomp_unique (hr : LinearIndependent K (Subtype.val ∘ r))
    {pn qm : ↥(parallelepiped K Λ r ∩ (Λ : Set V)) × (ι → ℕ)}
    (h : (pn.1 : V) + ∑ i, pn.2 i • (r i : V) = (qm.1 : V) + ∑ i, qm.2 i • (r i : V)) :
    pn = qm := sorry

/-- `Gordan.exists_decomp` and `Gordan.decomp_unique` combined. -/
theorem existsUnique_decomp (hr : LinearIndependent K (Subtype.val ∘ r)) (γ : V)
    (hγ : γ ∈ (cone K Λ r).latticePoints K Λ) :
    ∃! pn : ↥(parallelepiped K Λ r ∩ (Λ : Set V)) × (ι → ℕ),
      γ = (pn.1 : V) + ∑ i, pn.2 i • (r i : V) := by
  obtain ⟨pn, hpn⟩ := exists_decomp K Λ r γ hγ
  exact ⟨pn, hpn, fun _ hqm ↦ decomp_unique K Λ r hr (hqm.symm.trans hpn)⟩

omit [FloorRing K] in
/-- A decomposition is a lattice point of the cone. -/
lemma decomp_mem (pn : ↥(parallelepiped K Λ r ∩ (Λ : Set V)) × (ι → ℕ)) :
    (pn.1 : V) + ∑ i, pn.2 i • (r i : V) ∈ (cone K Λ r).latticePoints K Λ := by
  have hc : ∀ i, (r i : V) ∈ cone K Λ r := fun i ↦ Submodule.subset_span ⟨i, rfl⟩
  exact ⟨add_mem (parallelepiped_subset_cone K Λ r pn.1.2.1)
      (Submodule.sum_mem _ fun i _ ↦ nsmul_mem (hc i) _),
    add_mem pn.1.2.2 (Submodule.sum_mem _ fun i _ ↦ nsmul_mem (r i).2 _)⟩

/-- `Gordan.existsUnique_decomp`, packaged as a bijection. -/
noncomputable def decompEquiv (hr : LinearIndependent K (Subtype.val ∘ r)) :
    (↥(parallelepiped K Λ r ∩ (Λ : Set V)) × (ι → ℕ)) ≃ ↥((cone K Λ r).latticePoints K Λ) :=
  Equiv.ofBijective (fun pn ↦ ⟨_, decomp_mem K Λ r pn⟩)
    ⟨fun _ _ h ↦ decomp_unique K Λ r hr (congrArg Subtype.val h),
      fun γ ↦ (exists_decomp K Λ r γ γ.2).imp fun _ h ↦ Subtype.ext h.symm⟩

/-- The proposed set of generators. -/
def generators : Set V :=
  (parallelepiped K Λ r ∩ (Λ : Set V)) ∪ Set.range (Subtype.val ∘ r)

theorem generators_finite [Λ.IsLattice' K] : (generators K Λ r).Finite :=
  (parallelepiped_inter_lattice_finite K Λ r).union (Set.finite_range _)

/-- **Gordan's lemma**: the monoid of lattice points of the cone is generated by
`Gordan.generators`. -/
theorem gordan :
    AddSubmonoid.closure (generators K Λ r) = (cone K Λ r).latticePoints K Λ := by
  -- AI slop, need to understand and refactor
  refine le_antisymm (AddSubmonoid.closure_le.mpr ?_) fun γ hγ ↦ ?_
  · rintro x (⟨hxP, hxΛ⟩ | ⟨i, rfl⟩)
    · exact ⟨parallelepiped_subset_cone K Λ r hxP, hxΛ⟩
    · exact ⟨Submodule.subset_span ⟨i, rfl⟩, (r i).2⟩
  · obtain ⟨⟨p, n⟩, hpn⟩ := exists_decomp K Λ r γ hγ
    rw [hpn]
    refine add_mem (AddSubmonoid.subset_closure (Set.mem_union_left _ p.2))
      (AddSubmonoid.sum_mem _ fun i _ ↦ ?_)
    have hri : (r i : V) ∈ generators K Λ r := Or.inr ⟨i, rfl⟩
    exact nsmul_mem (AddSubmonoid.subset_closure hri) _

/-- **Gordan's lemma**, classical form: the monoid of lattice points is finitely generated. -/
theorem latticePoints_fg {ι : Type*} [Finite ι] (Λ : Submodule ℤ V) (r : ι → Λ)
    [Λ.IsLattice' K] : ((cone K Λ r).latticePoints K Λ).FG := by
  cases nonempty_fintype ι
  exact ⟨(generators_finite K Λ r).toFinset, by
    rw [Set.Finite.coe_toFinset]; exact gordan K Λ r⟩

end Gordan
