/-
Copyright (c) 2026 Louis Theran. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Louis Theran
-/

import Mathlib.LinearAlgebra.AffineSpace.FiniteDimensional
import Polyhedral.Mathlib.Geometry.Convex.Cone.Pointed.Finite.Face.Grade
import Polyhedral.Mathlib.Geometry.Convex.ConvexSpace.Dimension
import Polyhedral.Mathlib.Geometry.Convex.ConvexSpace.Polytope.Basic
import Polyhedral.Mathlib.Geometry.Convex.ConvexSpace.Polytope.KreinMilman
import Polyhedral.Mathlib.Geometry.Convex.ConvexSpace.Set.TangentCone

/-! # Finite generation of tangent cones of polytopes

`IsPolytope.tangentCone_singleton_fg` is the classical fact that the tangent cone of a polytope
at a single point (in particular, at a vertex) is generated by finitely many rays.
`IsPolytope.tangentCone_fg` extends this to the tangent cone over an arbitrary polytopal face
`F₀`, via `tangentCone_eq_tangentCone_singleton_sup_lineal`: the tangent cone over `F₀` is the
tangent cone at any single point of `F₀`, summed with the lineality space — and the lineality
space, being `(affineSpan R (F₀ : Set P)).direction` (`tangentCone_lineal`), is finitely generated
whenever `F₀` itself is. That's the whole proof; see the note before `IsPolytope.tangentCone_fg`
for why the combinatorial-looking machinery further down in this file isn't a shortcut to it. -/

noncomputable section

namespace Convexity

namespace ConvexSet

section Field

variable {R : Type*} [Field R] [LinearOrder R] [IsStrictOrderedRing R]
variable {M : Type*} [AddCommGroup M] [Module R M]
variable {P : Type*} [AddTorsor M P]

local instance : ConvexSpace R P := AddTorsor.toConvexSpace

variable [ConvexSpace R M] [IsModuleConvexSpace R M]

variable {K : ConvexSet R P}

open scoped Classical in
/-- **Explicit generators for the tangent cone of a polytope at a single point.** If
`K = convexHull R s` for a finite `s`, then `K.tangentCone {x₀} = hull {v -ᵥ x₀ | v ∈ s}` —
directly from `convexHull_tangentCone_eq_hull_vsub`. This is what makes
`IsPolytope.tangentCone_singleton_fg` (finite generation) true, and is reused verbatim to identify
the generators geometrically, e.g. as the edges out of a vertex
(`IsPolytope.not_mem_normalCone_singleton_iff`). -/
theorem tangentCone_singleton_eq_hull_vsub {s : Finset P}
    (hs : (K : Set P) = convexHull R (s : Set P)) (x₀ : P) :
    K.tangentCone ({x₀} : ConvexSet R P) =
      PointedCone.hull R ((s.image (· -ᵥ x₀) : Finset M) : Set M) := by
  classical
  rw [coe_eq_convexHull_iff.mp hs, convexHull_tangentCone_eq_hull_vsub]
  congr 1
  ext v
  simp only [Finset.coe_image, Set.mem_image, Finset.mem_coe, Set.mem_ofPred_eq]
  constructor
  · rintro ⟨y, hy, x, rfl, rfl⟩
    exact ⟨y, hy, rfl⟩
  · rintro ⟨y, hy, rfl⟩
    exact ⟨y, hy, x₀, rfl, rfl⟩

open scoped Classical in
/-- **The tangent cone of a polytope at a single point is generated by finitely many rays** —
the classical "cone over a vertex" picture, and the base case `IsPolytope.tangentCone_fg` reduces
to. Immediate from `tangentCone_singleton_eq_hull_vsub`. -/
theorem IsPolytope.tangentCone_singleton_fg (hK : IsPolytope R (K : Set P)) (x₀ : P) :
    (K.tangentCone ({x₀} : ConvexSet R P)).FG := by
  obtain ⟨s, hs⟩ := hK
  exact ⟨s.image (· -ᵥ x₀), (tangentCone_singleton_eq_hull_vsub hs x₀).symm⟩

omit [ConvexSpace R M] [IsModuleConvexSpace R M] in
/-- A submodule that is finitely generated as an `R`-module is also finitely generated as a
pointed cone (i.e. as a `Nonneg R`-module) — generate by a *negation-symmetric* finite set (if
`u` generates `S`, so does `u ∪ (-u)`, and a negation-symmetric generating set makes the pointed
cone hull coincide with the full submodule span, `PointedCone.hull_eq_span_of_neg_eq`). Needed
because `Submodule.FG` (used by `tangentCone_lineal`, an `R`-submodule fact) and `PointedCone.FG`
(what `IsPolytope.tangentCone_fg` needs) are, despite the shared name, different `Prop`s. -/
private theorem _root_.PointedCone.fg_ofSubmodule_of_fg {S : Submodule R M} (hS : S.FG) :
    (S : PointedCone R M).FG := by
  classical
  obtain ⟨u, hu⟩ := hS
  set u' : Finset M := u ∪ u.image Neg.neg with hu'_def
  have hsymm : -((u' : Finset M) : Set M) = (u' : Set M) := by
    apply Set.eq_of_subset_of_subset
    · intro v hv
      simp only [Set.mem_neg, hu'_def, Finset.coe_union, Finset.coe_image, Set.mem_union,
        Set.mem_image, Finset.mem_coe] at hv
      simp only [hu'_def, Finset.coe_union, Finset.coe_image, Set.mem_union, Set.mem_image,
        Finset.mem_coe]
      rcases hv with hv | ⟨w, hw, hwv⟩
      · exact Or.inr ⟨-v, hv, neg_neg v⟩
      · refine Or.inl ?_
        have hwv' : v = w := by rw [← neg_neg v, ← hwv, neg_neg]
        rw [hwv']; exact hw
    · intro v hv
      simp only [hu'_def, Finset.coe_union, Finset.coe_image, Set.mem_union, Set.mem_image,
        Finset.mem_coe] at hv
      simp only [Set.mem_neg, hu'_def, Finset.coe_union, Finset.coe_image, Set.mem_union,
        Set.mem_image, Finset.mem_coe]
      rcases hv with hv | ⟨w, hw, hwv⟩
      · exact Or.inr ⟨v, hv, rfl⟩
      · refine Or.inl ?_
        have hwv' : -v = w := by rw [← hwv, neg_neg]
        rw [hwv']; exact hw
  have hspan : Submodule.span R (u' : Set M) = S := by
    apply le_antisymm
    · apply Submodule.span_le.mpr
      simp only [hu'_def, Finset.coe_union, Finset.coe_image]
      apply Set.union_subset
      · rw [← hu]; exact Submodule.subset_span
      · rintro _ ⟨w, hw, rfl⟩
        exact S.neg_mem (hu ▸ Submodule.subset_span hw)
    · rw [← hu]
      apply Submodule.span_mono
      simp [hu'_def]
  refine ⟨u', ?_⟩
  change PointedCone.hull R (u' : Set M) = (S : PointedCone R M)
  rw [PointedCone.hull_eq_span_of_neg_eq R hsymm, hspan]

/-- **The tangent cone of a polytope over a polytopal face is finitely generated.** By
`tangentCone_eq_tangentCone_singleton_sup_lineal`, `K.tangentCone F₀` is the sup of
`K.tangentCone {x₀}` (finitely generated by `IsPolytope.tangentCone_singleton_fg`, for any
`x₀ ∈ F₀`) and `(K.tangentCone F₀).lineal = (affineSpan R (F₀ : Set P)).direction`
(`tangentCone_lineal`) — the direction of the affine span of a polytope is finite-dimensional
(`finiteDimensional_direction_affineSpan_of_finite`, via `affineSpan_convexHull_eq`), hence
`Submodule.FG`, hence `PointedCone.FG` once coerced (`PointedCone.fg_ofSubmodule_of_fg`). A sup of
finitely generated cones is finitely generated. -/
theorem IsPolytope.tangentCone_fg (hK : IsPolytope R (K : Set P)) {F₀ : ConvexSet R P}
    (hF₀K : F₀.IsFaceOf K) (hF₀ : IsPolytope R (F₀ : Set P))
    {x₀ : P} (hx₀ : x₀ ∈ F₀) :
    (K.tangentCone F₀).FG := by
  classical
  obtain ⟨t, ht⟩ := hF₀
  rw [tangentCone_eq_tangentCone_singleton_sup_lineal hF₀K hx₀]
  refine Submodule.FG.sup (IsPolytope.tangentCone_singleton_fg hK x₀) ?_
  rw [tangentCone_lineal hF₀K ⟨x₀, hx₀⟩]
  apply PointedCone.fg_ofSubmodule_of_fg
  rw [coe_eq_convexHull_iff.mp ht, coe_convexHull, affineSpan_convexHull_eq]
  exact (Submodule.fg_iff_finiteDimensional _).mpr
    (finiteDimensional_direction_affineSpan_of_finite R t.finite_toSet)

/-! ### Combinatorial side quest: grading and atom-level finite generation

The results below came out of trying to derive `IsPolytope.tangentCone_fg` purely from the
combinatorics of `Face K` (finite, atomistic, graded), with no explicit generating set. That
attempt didn't pan out (see the note on `IsPolytope.tangentCone_fg` above), but these facts are
true and reusable on their own: the polytope face lattice is graded by affine dimension
(`IsPolytope.finrank_covBy_of_covBy`), and each cone-face of a tangent cone corresponding to a
covering relation is finitely generated (`IsPolytope.tangentCone_fg_of_covBy`), via a general fact
about cones whose finrank exceeds their lineality's by exactly one
(`PointedCone.fg_of_finrank_lineal_add_one`). -/

omit [ConvexSpace R M] [IsModuleConvexSpace R M] in
private theorem covBy_Ici {a : Face K} {b c : Set.Ici a}
    (h : (b : Face K) ⋖ (c : Face K)) : b ⋖ c := by
  have hrange : Set.range (OrderEmbedding.subtype fun x : Face K => a ≤ x) = Set.Ici a := by
    ext x
    constructor
    · rintro ⟨⟨y, hy⟩, rfl⟩
      exact hy
    · intro hx
      exact ⟨⟨x, hx⟩, rfl⟩
  exact (Set.OrdConnected.apply_covBy_apply_iff (OrderEmbedding.subtype fun x => a ≤ x)
    (hrange ▸ Set.ordConnected_Ici)).mp h

/-- **Grading of the polytope face lattice via the tangent cone at a vertex.** If `F ⋖ G` in
`Face K` (`K` a polytope) and `F` is nonempty, then `G` has affine dimension exactly one more than
`F`. Proved by picking a vertex `x₀` of `F` (hence of `K`, by transitivity of `IsFaceOf`): since
`{x₀} ≤ F ≤ G`, the covering relation `F ⋖ G` transfers to `Set.Ici ({x₀} : Face K)`, and via
`tangentCone_ici_orderIso` corresponds to a covering relation in `Face (K.tangentCone {x₀})` — a
cone that is *already* known `FG` unconditionally (`tangentCone_singleton_fg`, no circularity),
so `PointedCone.FG.finrank_covBy` applies directly. Translating cone-rank back to `ConvexSet.rank`
via `finrank_tangentCone_eq_finrank` gives the result. -/
theorem IsPolytope.finrank_covBy_of_covBy (hK : IsPolytope R (K : Set P)) {F G : Face K}
    (hFG : F ⋖ G) (hFne : (F : Set P).Nonempty) :
    (G : ConvexSet R P).finrank = (F : ConvexSet R P).finrank + 1 := by
  classical
  have hFpoly : IsPolytope R ((F : ConvexSet R P) : Set P) :=
    IsPolytope.face_isPolytope hK F.isFaceOf
  have hVne : (Vertices R (F : ConvexSet R P)).Nonempty := by
    by_contra hempty
    rw [Set.not_nonempty_iff_eq_empty] at hempty
    have heq := IsPolytope.eq_convexHull_vertices R hFpoly
    have hFeq : (⟨((F : ConvexSet R P) : Set P), hFpoly.isConvexSet⟩ : ConvexSet R P) =
        (F : ConvexSet R P) := SetLike.coe_injective rfl
    rw [hFeq, hempty, convexHull_empty] at heq
    exact hFne.ne_empty (by rw [Face.coe_eq_toConvexSet_coe]; exact heq)
  obtain ⟨x₀, hx₀⟩ := hVne
  have hx₀F : ({x₀} : ConvexSet R P).IsFaceOf (F : ConvexSet R P) := hx₀
  have hx₀K : ({x₀} : ConvexSet R P).IsFaceOf K := hx₀F.trans F.isFaceOf
  set x₀Face : Face K := ⟨({x₀} : ConvexSet R P), hx₀K⟩ with hx₀Face_def
  have hx₀leF : x₀Face ≤ F := by
    rw [← Face.toConvexSet_le_toConvexSet]
    exact hx₀F.le
  have hx₀leG : x₀Face ≤ G := hx₀leF.trans hFG.le
  set F' : Set.Ici x₀Face := ⟨F, hx₀leF⟩ with hF'_def
  set G' : Set.Ici x₀Face := ⟨G, hx₀leG⟩ with hG'_def
  have hF'G' : F' ⋖ G' := covBy_Ici hFG
  have hx₀ne : (({x₀} : ConvexSet R P) : Set P).Nonempty := Set.singleton_nonempty x₀
  set e := tangentCone_ici_orderIso ({x₀} : ConvexSet R P) hx₀K hx₀ne with he_def
  have hcone : e.symm F' ⋖ e.symm G' := (apply_covBy_apply_iff e.symm).mpr hF'G'
  have hCfg : (K.tangentCone ({x₀} : ConvexSet R P)).FG :=
    IsPolytope.tangentCone_singleton_fg hK x₀
  have hstep := PointedCone.FG.finrank_covBy hCfg hcone
  have heqF : (e.symm F' : PointedCone.Face (K.tangentCone ({x₀} : ConvexSet R P))).finrank =
      (F : ConvexSet R P).finrank :=
    finrank_tangentCone_eq_finrank (Face.toConvexSet_le_toConvexSet.mpr hx₀leF) hx₀ne
  have heqG : (e.symm G' : PointedCone.Face (K.tangentCone ({x₀} : ConvexSet R P))).finrank =
      (G : ConvexSet R P).finrank :=
    finrank_tangentCone_eq_finrank (Face.toConvexSet_le_toConvexSet.mpr hx₀leG) hx₀ne
  rw [heqF, heqG] at hstep
  have := Nat.covBy_iff_add_one_eq.mp hstep
  omega

omit [ConvexSpace R M] [IsModuleConvexSpace R M] in
/-- **A cone whose finrank exceeds its lineality's finrank by exactly one is generated by the
lineality space plus a single ray.** The salient quotient `C.salientQuot` (always salient,
`salientQuot_salient`) has finrank exactly `1` (`finrank_eq_finrank_add_finrank_quot_span`), hence
is a ray `hull R {x}` (`ray_of_rank_one`); lifting `x` along the (surjective) quotient map to some
`v ∈ M` and reconstructing via `quot_eq_iff_sup_eq` shows `C = hull R {v} ⊔ C.lineal`. -/
private theorem _root_.PointedCone.fg_of_finrank_lineal_add_one {C : PointedCone R M}
    (hC : C.FinRank) (hlinealFG : C.lineal.FG)
    (h : C.finrank = Module.finrank R C.lineal + 1) : C.FG := by
  have hSubmoduleSpanEq : Submodule.span R ((C.lineal : PointedCone R M) : Set M) = C.lineal :=
    Submodule.span_eq C.lineal
  have hcoeFinrank : (C.lineal : PointedCone R M).finrank = Module.finrank R C.lineal := by
    unfold PointedCone.finrank
    rw [hSubmoduleSpanEq]
  have hadd := PointedCone.finrank_eq_finrank_add_finrank_quot_span hC (PointedCone.lineal_le C)
  rw [hSubmoduleSpanEq, hcoeFinrank] at hadd
  have hquotfinrank : C.salientQuot.finrank = 1 := by
    rw [PointedCone.salientQuot_eq_quot_lineal]; omega
  have hfinC : C.salientQuot.FinRank :=
    PointedCone.finRank_quot_submodule C C.lineal hC
  have hrank1 : C.salientQuot.rank = 1 := by
    have : Module.Finite R (Submodule.span R (C.salientQuot : Set (M ⧸ C.lineal))) :=
      Module.Finite.iff_fg.mpr hfinC
    have hcast : (C.salientQuot.finrank : Cardinal) = C.salientQuot.rank :=
      Cardinal.cast_toNat_of_lt_aleph0 (Module.rank_lt_aleph0 R _)
    rw [hquotfinrank] at hcast
    exact_mod_cast hcast.symm
  have hSal : C.salientQuot.Salient := PointedCone.salientQuot_salient C
  obtain ⟨x, hx⟩ := PointedCone.ray_of_rank_one hSal hrank1
  obtain ⟨v, hv⟩ := Submodule.mkQ_surjective C.lineal x
  have hveq : (PointedCone.hull R ({v} : Set M)).quot C.lineal = C.quot C.lineal := by
    simp only [PointedCone.quot_def, PointedCone.map_hull, Set.image_singleton,
      Submodule.mkQ_apply, hv]
    rw [← hx]
  have hCeq : C = PointedCone.hull R ({v} : Set M) ⊔ (C.lineal : PointedCone R M) := by
    have heq := PointedCone.quot_eq_iff_sup_eq.mp hveq
    rwa [sup_eq_left.mpr (PointedCone.lineal_le C), eq_comm] at heq
  rw [hCeq]
  exact Submodule.FG.sup ⟨{v}, by simp⟩ (PointedCone.fg_ofSubmodule_of_fg hlinealFG)

/-- **The cone-face of `K.tangentCone F₀` corresponding to a covering `F₀ ⋖ G` in `Face K` is
finitely generated.** Combines `span_tangentCone_eq_direction`/`finrank_tangentCone_eq_finrank`
(the cone's finrank is `G.finrank`), `tangentCone_lineal` (its lineal is
`affineSpan (F₀ : Set P)).direction`, of finrank `F₀.finrank`), `IsPolytope.finrank_covBy_of_covBy`
(the two differ by exactly `1`), and `PointedCone.fg_of_finrank_lineal_add_one` to conclude. -/
theorem IsPolytope.tangentCone_fg_of_covBy (hK : IsPolytope R (K : Set P)) {F₀ G : Face K}
    (hF₀G : F₀ ⋖ G) (hF₀ne : (F₀ : Set P).Nonempty) :
    ((G : ConvexSet R P).tangentCone (F₀ : ConvexSet R P)).FG := by
  have hGpoly : IsPolytope R ((G : ConvexSet R P) : Set P) :=
    IsPolytope.face_isPolytope hK G.isFaceOf
  have hF₀poly : IsPolytope R ((F₀ : ConvexSet R P) : Set P) :=
    IsPolytope.face_isPolytope hK F₀.isFaceOf
  have hF₀leG : (F₀ : ConvexSet R P) ≤ (G : ConvexSet R P) :=
    Face.toConvexSet_le_toConvexSet.mpr hF₀G.le
  have hF₀FaceG : (F₀ : ConvexSet R P).IsFaceOf (G : ConvexSet R P) :=
    (IsFaceOf.isFaceOf_iff (F₀ : ConvexSet R P) G.isFaceOf).mpr ⟨hF₀leG, F₀.isFaceOf⟩
  apply PointedCone.fg_of_finrank_lineal_add_one
  · change (Submodule.span R
      (((G : ConvexSet R P).tangentCone (F₀ : ConvexSet R P) : PointedCone R M) : Set M)).FG
    rw [span_tangentCone_eq_direction hF₀leG hF₀ne]
    obtain ⟨t, ht⟩ := hGpoly
    rw [coe_eq_convexHull_iff.mp ht, coe_convexHull, affineSpan_convexHull_eq]
    exact (Submodule.fg_iff_finiteDimensional _).mpr
      (finiteDimensional_direction_affineSpan_of_finite R t.finite_toSet)
  · rw [tangentCone_lineal hF₀FaceG hF₀ne]
    obtain ⟨t, ht⟩ := hF₀poly
    rw [coe_eq_convexHull_iff.mp ht, coe_convexHull, affineSpan_convexHull_eq]
    exact (Submodule.fg_iff_finiteDimensional _).mpr
      (finiteDimensional_direction_affineSpan_of_finite R t.finite_toSet)
  · rw [finrank_tangentCone_eq_finrank hF₀leG hF₀ne, tangentCone_lineal hF₀FaceG hF₀ne]
    exact IsPolytope.finrank_covBy_of_covBy hK hF₀G hF₀ne

end Field

end ConvexSet

end Convexity
