/-
Copyright (c) 2026 Louis Theran. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Louis Theran
-/

import Mathlib.LinearAlgebra.AffineSpace.FiniteDimensional
import Polyhedral.Mathlib.Geometry.Convex.ConvexSpace.Dimension
import Polyhedral.Mathlib.Geometry.Convex.ConvexSpace.Polytope.Basic
import Polyhedral.Mathlib.Geometry.Convex.ConvexSpace.Set.TangentCone

/-! # Finite generation of tangent cones of polytopes

`IsPolytope.tangentCone_singleton_fg` is the classical fact that the tangent cone of a polytope
at a single point (in particular, at a vertex) is generated by finitely many rays.
`IsPolytope.tangentCone_fg` extends this to the tangent cone over an arbitrary polytopal face
`F₀`, via `tangentCone_eq_tangentCone_singleton_sup_lineal`: the tangent cone over `F₀` is the
tangent cone at any single point of `F₀`, summed with the lineality space — and the lineality
space, being `(affineSpan R (F₀ : Set P)).direction` (`tangentCone_lineal`), is finitely generated
whenever `F₀` itself is. -/

noncomputable section

namespace Convexity

namespace ConvexSet

section Field

variable {R : Type*} [Field R] [LinearOrder R] [IsStrictOrderedRing R]
variable {M : Type*} [AddCommGroup M] [Module R M]
variable {P : Type*} [AddTorsor M P]

local instance : ConvexSpace R P := AddTorsor.toConvexSpace

variable [ConvexSpace R M] [IsModuleConvexSpace R M]

variable {K : ConvexSet R P}

/-- **The tangent cone of a polytope at a single point is generated by finitely many rays** —
the classical "cone over a vertex" picture, and the base case `IsPolytope.tangentCone_fg` reduces
to. Directly from `convexHull_tangentCone_eq_hull_vsub`: if `K = convexHull R s` for a finite `s`,
then `K.tangentCone {x₀} = hull {v -ᵥ x₀ | v ∈ s}`, manifestly generated by the finite set
`s.image (· -ᵥ x₀)`. -/
theorem IsPolytope.tangentCone_singleton_fg (hK : IsPolytope R (K : Set P)) (x₀ : P) :
    (K.tangentCone ({x₀} : ConvexSet R P)).FG := by
  classical
  obtain ⟨s, hs⟩ := hK
  rw [coe_eq_convexHull_iff.mp hs, convexHull_tangentCone_eq_hull_vsub]
  refine ⟨s.image (· -ᵥ x₀), ?_⟩
  congr 1
  ext v
  simp only [Finset.coe_image, Set.mem_image, Finset.mem_coe, Set.mem_ofPred_eq]
  constructor
  · rintro ⟨y, hy, rfl⟩
    exact ⟨y, hy, x₀, rfl, rfl⟩
  · rintro ⟨y, hy, x, rfl, rfl⟩
    exact ⟨y, hy, rfl⟩

omit [ConvexSpace R M] [IsModuleConvexSpace R M] in
/-- A submodule that is finitely generated as an `R`-module is also finitely generated as a
pointed cone (i.e. as a `Nonneg R`-module) — generate by a *negation-symmetric* finite set (if
`u` generates `S`, so does `u ∪ (-u)`, and a negation-symmetric generating set makes the pointed
cone hull coincide with the full submodule span, `PointedCone.hull_eq_span_of_neg_eq`). Needed
because `Submodule.FG` (used by `tangentCone_lineal`, an `R`-submodule fact) and `PointedCone.FG`
(what `IsPolytope.tangentCone_fg` needs) are, despite the shared name, different `Prop`s. -/
private theorem _root_.PointedCone.fg_ofSubmodule_of_fg {S : Submodule R M} (hS : S.FG) :
    (S : PointedCone R M).FG := by
  classical
  obtain ⟨u, hu⟩ := hS
  set u' : Finset M := u ∪ u.image Neg.neg with hu'_def
  have hsymm : -((u' : Finset M) : Set M) = (u' : Set M) := by
    apply Set.eq_of_subset_of_subset
    · intro v hv
      simp only [Set.mem_neg, hu'_def, Finset.coe_union, Finset.coe_image, Set.mem_union,
        Set.mem_image, Finset.mem_coe] at hv
      simp only [hu'_def, Finset.coe_union, Finset.coe_image, Set.mem_union, Set.mem_image,
        Finset.mem_coe]
      rcases hv with hv | ⟨w, hw, hwv⟩
      · exact Or.inr ⟨-v, hv, neg_neg v⟩
      · refine Or.inl ?_
        have hwv' : v = w := by rw [← neg_neg v, ← hwv, neg_neg]
        rw [hwv']; exact hw
    · intro v hv
      simp only [hu'_def, Finset.coe_union, Finset.coe_image, Set.mem_union, Set.mem_image,
        Finset.mem_coe] at hv
      simp only [Set.mem_neg, hu'_def, Finset.coe_union, Finset.coe_image, Set.mem_union,
        Set.mem_image, Finset.mem_coe]
      rcases hv with hv | ⟨w, hw, hwv⟩
      · exact Or.inr ⟨v, hv, rfl⟩
      · refine Or.inl ?_
        have hwv' : -v = w := by rw [← hwv, neg_neg]
        rw [hwv']; exact hw
  have hspan : Submodule.span R (u' : Set M) = S := by
    apply le_antisymm
    · apply Submodule.span_le.mpr
      simp only [hu'_def, Finset.coe_union, Finset.coe_image]
      apply Set.union_subset
      · rw [← hu]; exact Submodule.subset_span
      · rintro _ ⟨w, hw, rfl⟩
        exact S.neg_mem (hu ▸ Submodule.subset_span hw)
    · rw [← hu]
      apply Submodule.span_mono
      simp [hu'_def]
  refine ⟨u', ?_⟩
  change PointedCone.hull R (u' : Set M) = (S : PointedCone R M)
  rw [PointedCone.hull_eq_span_of_neg_eq R hsymm, hspan]

/-- **The tangent cone of a polytope over a polytopal face is finitely generated.** By
`tangentCone_eq_tangentCone_singleton_sup_lineal`, `K.tangentCone F₀` is the sup of
`K.tangentCone {x₀}` (finitely generated by `IsPolytope.tangentCone_singleton_fg`, for any
`x₀ ∈ F₀`) and `(K.tangentCone F₀).lineal = (affineSpan R (F₀ : Set P)).direction`
(`tangentCone_lineal`) — the direction of the affine span of a polytope is finite-dimensional
(`finiteDimensional_direction_affineSpan_of_finite`, via `affineSpan_convexHull_eq`), hence
`Submodule.FG`, hence `PointedCone.FG` once coerced (`PointedCone.fg_ofSubmodule_of_fg`). A sup of
finitely generated cones is finitely generated. -/
theorem IsPolytope.tangentCone_fg (hK : IsPolytope R (K : Set P)) {F₀ : ConvexSet R P}
    (hF₀K : F₀.IsFaceOf K) (hF₀ : IsPolytope R (F₀ : Set P))
    {x₀ : P} (hx₀ : x₀ ∈ F₀) :
    (K.tangentCone F₀).FG := by
  classical
  obtain ⟨t, ht⟩ := hF₀
  rw [tangentCone_eq_tangentCone_singleton_sup_lineal hF₀K hx₀]
  refine Submodule.FG.sup (IsPolytope.tangentCone_singleton_fg hK x₀) ?_
  rw [tangentCone_lineal hF₀K ⟨x₀, hx₀⟩]
  apply PointedCone.fg_ofSubmodule_of_fg
  rw [coe_eq_convexHull_iff.mp ht, coe_convexHull, affineSpan_convexHull_eq]
  exact (Submodule.fg_iff_finiteDimensional _).mpr
    (finiteDimensional_direction_affineSpan_of_finite R t.finite_toSet)

end Field

end ConvexSet

end Convexity
