/-
Copyright (c) 2026 . All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors:
-/

import Polyhedral.Mathlib.LinearAlgebra.AffineSpace.TangentCone
import Polyhedral.Mathlib.Geometry.Convex.ConvexSpace.Set.TangentCone
import Polyhedral.Mathlib.Geometry.Convex.ConvexSpace.Polytope.Basic
import Polyhedral.Mathlib.Geometry.Convex.ConvexSpace.Polytope.Face
import Polyhedral.Mathlib.Geometry.Convex.ConvexSpace.Polytope.KreinMilman
import Polyhedral.Mathlib.Geometry.Convex.Cone.Pointed.Convexity
import Polyhedral.Mathlib.Geometry.Convex.Cone.Pointed.Finite.Face.KreinMilman
import Polyhedral.Mathlib.Geometry.Convex.Cone.Pointed.Polyhedral.Basic
import Polyhedral.Mathlib.Geometry.Convex.Cone.Pointed.Polyhedral.Faces
import Polyhedral.Mathlib.Geometry.Convex.Cone.Pointed.Face.Exposed

/-! This file specializes the tangent cone of `Affine.TangentCone` to polytopes, and proves that
the tangent cone at a vertex of a polytope is generated by the edges of the polytope emanating
from that vertex.

The pieces:

1. `IsPolytope.tangentCone_fg` / `IsPolytope.tangentCone_salient`: the tangent cone of a polytope
   at a vertex is finitely generated (directly from `s` being the convex hull of a finite set;
   `PointedCone.hull_convexHull` absorbs the convex combinations) and salient (pointed).
2. `IsPolytope.tangentCone_eq_hull_rays`: combining (1) with the Krein-Milman theorem for cones
   (`PointedCone.FG.krein_milman`, already proved in `Cone.Pointed.Finite.Face.KreinMilman`) shows
   the tangent cone is the hull of finitely many of its own ray faces.
3. `isFaceOf_sep` / `tangentCone_inf_ker_eq_tangentCone_sep` (the bridge lemma): cutting the
   tangent cone by a hyperplane `φ` exposing one of its faces corresponds exactly to the tangent
   cone, still at `x`, of the face `{y ∈ s | φ (y -ᵥ x) = 0}` cut out of `s` by the same
   hyperplane — and `isFaceOf_sep` shows this really is a face of `s` in the classical
   (extreme-subset) `ConvexSet.IsFaceOf` sense, not merely a cone-face of the tangent cone.
4. `IsPolytope.exists_edge_of_ray_isFaceOf`: every nonzero ray face of the tangent cone is,
   via (3) together with Krein-Milman for polytopes (`IsPolytope.eq_convexHull_extremePoints`,
   proved by transporting (2) through homogenization), genuinely the direction of an edge: there
   is a vertex `y` of `s` with `y -ᵥ x` a positive multiple of the ray, and `convexHull k {x, y}`
   is a face of `s`.
5. `IsPolytope.tangentCone_eq_hull_edgeVectors`: combining (2) and (4), the main theorem — the
   tangent cone at a vertex is generated by finitely many edge vectors. -/

namespace Affine

open Convexity PointedCone Module

section Polytope

variable (k : Type*) {V P : Type*} [AddCommGroup V] [AddTorsor V P]
variable {s : Set P} (x : s)
variable [Field k] [Module k V] [LinearOrder k] [IsStrictOrderedRing k]

attribute [local instance] AddTorsor.toConvexSpace
attribute [local instance] Convexity.ConvexSpace.ofModule
local instance : Convexity.IsModuleConvexSpace k V := .ofModule

/-- The tangent cone of a polytope at any of its points is finitely generated. -/
theorem IsPolytope.tangentCone_fg (hs : IsPolytope k s) :
    (tangentCone k s x).FG := by
  obtain ⟨t, rfl⟩ := hs
  rw [tangentCone_eq_hull_image, (isAffineMap_vsub_right k (x : P)).image_convexHull,
    PointedCone.hull_convexHull]
  exact Submodule.fg_span (t.finite_toSet.image _)

/-- The tangent cone at a vertex (extreme point) of a polytope is salient. -/
theorem IsPolytope.tangentCone_salient (hs : IsPolytope k s)
    (hx : IsExtremePoint k s (x : P)) : (tangentCone k s x).Salient :=
  Salient.tangentCone_of_isExtremePoint k s x hs.isConvexSet hx

/-- The tangent cone at a vertex of a polytope is the cone hull of a finite set of
representatives of its edges (its 1-dimensional faces, i.e. rays). This is Krein-Milman for
cones, specialized to vertex tangent cones of polytopes. -/
theorem IsPolytope.tangentCone_eq_hull_rays (hs : IsPolytope k s)
    (hx : IsExtremePoint k s (x : P)) :
    ∃ r : Finset V, PointedCone.hull k (r : Set V) = tangentCone k s x ∧
      ∀ v ∈ r, (k ∙₊ v).IsFaceOf (tangentCone k s x) :=
  FG.krein_milman (IsPolytope.tangentCone_fg k x hs) (IsPolytope.tangentCone_salient k x hs hx)

/-- The point `x`, viewed as a member of the exposed face of `s` cut out by `φ`. -/
private def sepMem {φ : Dual k V} (hφx : φ ((x : P) -ᵥ (x : P)) = 0) :
    ↥{y ∈ s | φ (y -ᵥ (x : P)) = 0} :=
  ⟨(x : P), x.2, hφx⟩

/-- The set of points of `s` whose chordal direction from `x` lies in a given subcone `F` of the
tangent cone. This is `s`, "cut" by `F`. -/
def sepSet (F : PointedCone k V) : Set P := {y ∈ s | y -ᵥ (x : P) ∈ F}

/-- `sepSet` is convex: it is the intersection of `s` with the preimage of the (automatically
convex, being a `PointedCone`) set `F` under the affine map `y ↦ y -ᵥ x`. -/
theorem isConvexSet_sepSet (hsc : IsConvexSet k s) (F : PointedCone k V) :
    IsConvexSet k (sepSet k x F) :=
  hsc.inter (IsConvexSet.preimage (isAffineMap_vsub_right k (x : P)) F.isConvexSet)

/-- If `F` is a face of the tangent cone at `x`, then `sepSet F` (`s` cut by `F`) is a face of
`s`, in the classical (extreme-subset) `ConvexSet.IsFaceOf` sense. This is the general fact
underlying the bridge lemma: a point `w` of `sepSet F` can only be a proper convex combination of
two points `a, b ∈ s` if `a -ᵥ x` and `b -ᵥ x` themselves already lie in `F` — they are chordal
directions of `s` (hence in the tangent cone), and a positive combination of them lands in the
subcone `F`, so `F` being a face forces each individually into `F`.

The converse holds too when `F` is *saturated*, i.e. `F = tangentCone k T x` for the resulting
`T := sepSet F` itself (this is what the bridge lemma establishes for `F` exposed); for a general
subcone `F` the converse can fail (e.g. `F` could avoid every chordal direction of `s` without
itself being a face of the tangent cone), so it is not proved here. -/
theorem isFaceOf_sepSet (hsc : IsConvexSet k s) {F : PointedCone k V}
    (hF : F.IsFaceOf (tangentCone k s x)) :
    Convexity.ConvexSet.IsFaceOf
      (⟨sepSet k x F, isConvexSet_sepSet k x hsc F⟩ : Convexity.ConvexSet k P) ⟨s, hsc⟩ where
  le := fun _ hy => hy.1
  left_mem_of_mem_openSegment := by
    intro a ha b hb w hw hwseg
    obtain ⟨p, q, hp, hq, hpq, hcomb⟩ := hwseg
    rw [AddTorsor.convexCombPair_eq_lineMap] at hcomb
    have hrw : AffineMap.lineMap b a p -ᵥ (x : P)
        = (1 - p) • (b -ᵥ (x : P)) + p • (a -ᵥ (x : P)) := by
      simp only [AffineMap.lineMap_apply, vadd_vsub_assoc]
      rw [show a -ᵥ b = (a -ᵥ (x : P)) - (b -ᵥ (x : P)) from
        (vsub_sub_vsub_cancel_right a b (x : P)).symm, smul_sub]
      module
    have hwmem : (1 - p) • (b -ᵥ (x : P)) + p • (a -ᵥ (x : P)) ∈ F := by
      rw [← hrw, hcomb]; exact hw.2
    have haC : a -ᵥ (x : P) ∈ tangentCone k s x := vsub_mem_tangentCone k s x ha
    have hbC : b -ᵥ (x : P) ∈ tangentCone k s x := vsub_mem_tangentCone k s x hb
    exact ⟨ha, hF.mem_of_smul_add_smul_mem_right hbC haC (by linarith) hp hwmem⟩

/-- The set `{y ∈ s | φ (y -ᵥ x) = 0}` cut out by `φ` is convex: it is `sepSet k x φ.ker`. -/
private theorem isConvexSet_sep (hsc : IsConvexSet k s) (φ : Dual k V) :
    IsConvexSet k {y ∈ s | φ (y -ᵥ (x : P)) = 0} := by
  have hset : {y ∈ s | φ (y -ᵥ (x : P)) = 0} = sepSet k x (φ.ker : PointedCone k V) := by
    simp [sepSet]
  rw [hset]; exact isConvexSet_sepSet k x hsc _

/-- The bridge lemma's exposed set `{y ∈ s | φ (y -ᵥ x) = 0}` is a genuine face of `s`, in the
classical (extreme-subset) polytope sense, not merely a cone-face of the tangent cone. This is
the piece that actually connects a ray-face of the tangent cone back to the polytope `s` itself.
It is `isFaceOf_sepSet` applied to `F := tangentCone k s x ⊓ φ.ker`, which is a face of the
tangent cone since `φ` exposes it (`IsExposedFaceOf.isFaceOf`). -/
theorem isFaceOf_sep (hsc : IsConvexSet k s) (φ : Dual k V)
    (hφ : tangentCone k s x ≤ φ.nonneg) :
    Convexity.ConvexSet.IsFaceOf
      (⟨{y ∈ s | φ (y -ᵥ (x : P)) = 0}, isConvexSet_sep k x hsc φ⟩ : Convexity.ConvexSet k P)
      ⟨s, hsc⟩ := by
  have hface : (tangentCone k s x ⊓ (φ.ker : PointedCone k V)).IsFaceOf (tangentCone k s x) :=
    PointedCone.IsExposedFaceOf.isFaceOf ⟨φ, hφ, rfl⟩
  have hset : {y ∈ s | φ (y -ᵥ (x : P)) = 0}
      = sepSet k x (tangentCone k s x ⊓ (φ.ker : PointedCone k V)) := by
    ext y
    simp only [sepSet, Set.mem_setOf_eq, Submodule.mem_inf, SetLike.mem_coe, LinearMap.mem_ker,
      and_congr_right_iff]
    exact fun hys => ⟨fun h => ⟨vsub_mem_tangentCone k s x hys, h⟩, fun h => h.2⟩
  simpa only [hset] using isFaceOf_sepSet k x hsc hface

/-- General cone fact underlying the bridge lemma: the exposed face of `hull k s` cut out by a
functional `φ` that is nonnegative on it is the hull of the elements of `s` on which `φ`
vanishes. The inclusion `⊇` is immediate since `φ.ker` is a submodule, hence closed under the
positive combinations forming the hull. The inclusion `⊆` is where the hypothesis is used: writing
`a ∈ hull k s` as a nonnegative combination `∑ cᵢ sᵢ` of generators `sᵢ ∈ s`, each term `cᵢ φ(sᵢ)`
is nonnegative (as `φ ≥ 0` on `s`), and they sum to `φ a = 0`, so minimality forces every term with
`cᵢ ≠ 0` to individually vanish, i.e. every generator actually used already lies in `s ∩ φ.ker`. -/
private lemma hull_inf_ker_eq_hull_inter {W : Type*} [AddCommGroup W] [Module k W]
    {s : Set W} {φ : Dual k W} (hφ : PointedCone.hull k s ≤ φ.nonneg) :
    PointedCone.hull k s ⊓ (φ.ker : PointedCone k W) =
      PointedCone.hull k (s ∩ (φ.ker : Set W)) := by
  refine le_antisymm ?_ (le_inf (PointedCone.hull_mono Set.inter_subset_left)
    (Submodule.span_le.mpr fun v hv => hv.2))
  rintro a ⟨ha, ha0⟩
  obtain ⟨c, hcs, hc0, rfl⟩ := PointedCone.mem_hull_set.mp ha
  have ha0' : φ (c.sum fun m r => r • m) = 0 := ha0
  rw [Finsupp.sum, map_sum] at ha0'
  simp only [map_smul, smul_eq_mul] at ha0'
  have hnn : ∀ m ∈ c.support, 0 ≤ c m * φ m :=
    fun m hm => mul_nonneg (hc0 m) (hφ (PointedCone.subset_hull (hcs hm)))
  have hz := (Finset.sum_eq_zero_iff_of_nonneg hnn).mp ha0'
  refine PointedCone.mem_hull_set.mpr ⟨c, fun m hm => ⟨hcs hm, ?_⟩, hc0, rfl⟩
  rcases mul_eq_zero.mp (hz m hm) with h | h
  · exact absurd h (Finsupp.mem_support_iff.mp hm)
  · exact h

/-- Bridge lemma. Cutting the tangent cone at `x` by the hyperplane exposing a face of the
tangent cone (a functional `φ` that is nonnegative on the whole tangent cone) gives exactly the
tangent cone, still at `x`, of the corresponding face of `s`: the subset of `s` on which `φ`
(recentred at `x`) vanishes. This is the "saturated" case of `isFaceOf_sepSet`, where the exposed
`F := tangentCone k s x ⊓ φ.ker` is recovered exactly as the tangent cone of the face it cuts
out. -/
theorem tangentCone_inf_ker_eq_tangentCone_sep (φ : Dual k V)
    (hφ : tangentCone k s x ≤ φ.nonneg) :
    tangentCone k s x ⊓ (φ.ker : PointedCone k V) =
      tangentCone k {y ∈ s | φ (y -ᵥ (x : P)) = 0} (sepMem k x (by simp)) := by
  simp only [tangentCone_eq_hull_image, sepMem] at hφ ⊢
  rw [hull_inf_ker_eq_hull_inter k hφ]
  congr 1
  ext v
  simp only [Set.mem_inter_iff, Set.mem_image, Set.mem_ofPred_eq, SetLike.mem_coe,
    LinearMap.mem_ker]
  constructor
  · rintro ⟨⟨y, hys, rfl⟩, hφv⟩
    exact ⟨y, ⟨hys, hφv⟩, rfl⟩
  · rintro ⟨y, ⟨hys, hφy⟩, rfl⟩
    exact ⟨⟨y, hys, rfl⟩, hφy⟩

/-- If the tangent cone of a set `T` at one of its points is a ray, `T` lies on the line through
that point in the ray's direction. TODO: this belongs in a more general file once one exists for
facts relating `tangentCone` to affine dimension (see `ConvexSpace/Dimension.lean`). -/
private theorem subset_affineSpan_pair_of_tangentCone_eq_ray {T : Set P} (x' : T) {v : V}
    (hT : tangentCone k T x' = k ∙₊ v) :
    T ⊆ affineSpan k ({(x' : P), v +ᵥ (x' : P)} : Set P) := by
  intro z hz
  have hmem : z -ᵥ (x' : P) ∈ tangentCone k T x' := vsub_mem_tangentCone k T x' hz
  rw [hT] at hmem
  obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp hmem
  refine mem_affineSpan_pair_iff_exists_lineMap_eq.mpr ⟨c, ?_⟩
  have hc' : (↑c : k) • v = z -ᵥ (x' : P) := by exact_mod_cast hc
  rw [AffineMap.lineMap_apply, vadd_vsub, hc', vsub_vadd]

/-- A finite set of points, all lying on a common line and all extreme in a common ambient
convex set, has at most two elements: parametrizing the line by the base field via `lineMap`, a
third point strictly between the extremes (by that parameter) would be a nontrivial convex
combination of the other two, contradicting its own extremality. TODO: this belongs in a more
general file about convexity on a line once one exists (see `ConvexSpace/Dimension.lean`). -/
private theorem card_le_two_of_forall_isFaceOf_of_subset_affineSpan_pair
    {a b : P} {C : Convexity.ConvexSet k P} {E : Finset P}
    (hEC : (E : Set P) ⊆ C) (hEspan : (E : Set P) ⊆ affineSpan k ({a, b} : Set P))
    (hext : ∀ z ∈ E, ({z} : Convexity.ConvexSet k P).IsFaceOf C) : E.card ≤ 2 := by
  classical
  rcases E.eq_empty_or_nonempty with rfl | hEne
  · simp
  set v : V := b -ᵥ a with hvdef
  have htex : ∀ z ∈ E, ∃ t : k, z -ᵥ a = t • v := by
    intro z hz
    obtain ⟨t, ht⟩ := mem_affineSpan_pair_iff_exists_lineMap_eq.mp (hEspan hz)
    exact ⟨t, by rw [← ht, AffineMap.lineMap_apply, vadd_vsub, hvdef]⟩
  let tOf : P → k := fun z => if hz : z ∈ E then (htex z hz).choose else 0
  have hteq : ∀ z ∈ E, z -ᵥ a = tOf z • v := by
    intro z hz; simp only [tOf, dif_pos hz]; exact (htex z hz).choose_spec
  have htinj : ∀ p ∈ E, ∀ q ∈ E, tOf p = tOf q → p = q := by
    intro p hp q hq he
    have hpq : p -ᵥ a = q -ᵥ a := by rw [hteq p hp, hteq q hq, he]
    have h1 := congrArg (· +ᵥ a) hpq
    simpa using h1
  obtain ⟨tmin, htminE, htminle⟩ := Finset.exists_min_image E tOf hEne
  obtain ⟨tmax, htmaxE, htmaxle⟩ := Finset.exists_max_image E tOf hEne
  have hmid : ∀ z ∈ E, z = tmin ∨ z = tmax := by
    intro z hz
    by_contra hcon
    push_neg at hcon
    obtain ⟨hzne_min, hzne_max⟩ := hcon
    have h1 : tOf tmin ≤ tOf z := htminle z hz
    have h2 : tOf z ≤ tOf tmax := htmaxle z hz
    have h1' : tOf tmin < tOf z :=
      lt_of_le_of_ne h1 (fun he => hzne_min (htinj tmin htminE z hz he).symm)
    have h2' : tOf z < tOf tmax :=
      lt_of_le_of_ne h2 (fun he => hzne_max (htinj z hz tmax htmaxE he))
    have hden : 0 < tOf tmax - tOf tmin := by linarith
    set t : k := (tOf z - tOf tmin) / (tOf tmax - tOf tmin) with htdef
    have ht0 : 0 < t := div_pos (by linarith) hden
    have ht1 : t < 1 := (div_lt_one hden).mpr (by linarith)
    have hkey : AffineMap.lineMap tmin tmax t = z := by
      have hrw : AffineMap.lineMap tmin tmax t -ᵥ a
          = (1 - t) • (tmin -ᵥ a) + t • (tmax -ᵥ a) := by
        simp only [AffineMap.lineMap_apply, vadd_vsub_assoc]
        rw [show tmax -ᵥ tmin = (tmax -ᵥ a) - (tmin -ᵥ a) from
          (vsub_sub_vsub_cancel_right tmax tmin a).symm, smul_sub]
        module
      rw [hteq tmin htminE, hteq tmax htmaxE] at hrw
      have hcoef : (1 - t) • tOf tmin • v + t • tOf tmax • v = tOf z • v := by
        have hte : (1 - t) * tOf tmin + t * tOf tmax = tOf z := by rw [htdef]; field_simp; ring
        rw [smul_smul, smul_smul, ← add_smul, hte]
      rw [hcoef, ← hteq z hz] at hrw
      have h1 := congrArg (· +ᵥ a) hrw
      simpa using h1
    have hface_z : ({z} : Convexity.ConvexSet k P).IsFaceOf C := hext z hz
    have hseg : z ∈ Convexity.openSegment k tmax tmin := by
      refine ⟨t, 1 - t, ht0, by linarith, by ring, ?_⟩
      rw [AddTorsor.convexCombPair_eq_lineMap]
      exact hkey
    have hzz : z ∈ ({z} : Convexity.ConvexSet k P) := rfl
    have hres := hface_z.left_mem_of_mem_openSegment (hEC htmaxE) (hEC htminE) hzz hseg
    exact hzne_max (id hres : tmax = z).symm
  have hss : E ⊆ ({tmin, tmax} : Finset P) := by
    intro z hz; rcases hmid z hz with h | h <;> simp [h]
  exact (Finset.card_le_card hss).trans
    ((Finset.card_insert_le _ _).trans (by simp))

open Convexity.ConvexSet in
/-- The main theorem: every nonzero ray face of the tangent cone at a vertex `x` of a polytope
`s` is genuinely the direction of an edge of `s` at `x`, in the classical (extreme-subset) sense:
there is a vertex `y` of `s` with `y -ᵥ x` a positive multiple of the ray's direction `v`, and
the segment `convexHull k {x, y}` is a face of `s`.

The proof: since `k ∙₊ v` is a face of the (polyhedral) tangent cone, it is exposed by some `φ`
(`IsFaceOf.isExposed_of_polyhedral`); the bridge lemma identifies the corresponding cut
`{y ∈ s | φ (y -ᵥ x) = 0}` (a genuine face `F` of `s`, by `isFaceOf_sep`) as having tangent cone
at `x` exactly `k ∙₊ v`. Since `F` is a polytope (`IsPolytope.face_isPolytope`), Krein-Milman for
polytopes writes it as the hull of finitely many of its own extreme points; `x` is one of them
(`isFaceOf_of_isExtremePoint`, restricted to `F`), and since every point of `F` lies on the ray
through `v` from `x` (from the tangent cone identification), the extreme points of `F` colinear
with `x` along that ray number at most two: any third, strictly between the extremes, would fail
to be extreme. Since `v ≠ 0`, there must be a second one, `y`. -/
theorem IsPolytope.exists_edge_of_ray_isFaceOf (hs : IsPolytope k s)
    (hx : IsExtremePoint k s (x : P)) {v : V} (hv0 : v ≠ 0)
    (hface : (k ∙₊ v).IsFaceOf (tangentCone k s x)) :
    ∃ y ∈ s, ({y} : Convexity.ConvexSet k P).IsFaceOf ⟨s, hs.isConvexSet⟩ ∧
      ∃ c : k, 0 < c ∧ y -ᵥ (x : P) = c • v ∧
        (Convexity.ConvexSet.convexHull k ({(x : P), y} : Set P)).IsFaceOf
          ⟨s, hs.isConvexSet⟩ := by
  classical
  have hpoly : (tangentCone k s x).IsPolyhedral := (IsPolytope.tangentCone_fg k x hs).isPolyhedral
  obtain ⟨φ, hφ, hφeq⟩ := PointedCone.IsFaceOf.isExposed_of_polyhedral hpoly hface
  set F : Set P := {y ∈ s | φ (y -ᵥ (x : P)) = 0}
  have hFconv : IsConvexSet k F := isConvexSet_sep k x hs.isConvexSet φ
  set Fs : Convexity.ConvexSet k P := ⟨F, hFconv⟩
  have hx'mem : φ ((x : P) -ᵥ (x : P)) = 0 := by simp
  set x' : ↥F := sepMem k x hx'mem
  have hFface : Fs.IsFaceOf ⟨s, hs.isConvexSet⟩ := isFaceOf_sep k x hs.isConvexSet φ hφ
  have hcone_eq : (k ∙₊ v : PointedCone k V) = tangentCone k F x' := by
    rw [hφeq]; exact tangentCone_inf_ker_eq_tangentCone_sep k x φ hφ
  have hFpoly : IsPolytope k F := IsPolytope.face_isPolytope hs hFface
  let W := CanonicalHomogenization k P
  let := IsModuleConvexSpace.ofAddTorsor (R := k) (V := W)
  obtain ⟨E_F, hE_Fsub, hE_Feq, hE_Fext⟩ :=
    IsPolytope.eq_convexHull_extremePoints W hFpoly
  have hxF : (x : P) ∈ F := x'.2
  have hxExtS : ({(x : P)} : Convexity.ConvexSet k P).IsFaceOf ⟨s, hs.isConvexSet⟩ :=
    ConvexSet.isFaceOf_of_isExtremePoint k s x hs.isConvexSet hx
  have hxExtF : ({(x : P)} : Convexity.ConvexSet k P).IsFaceOf Fs :=
    (Convexity.ConvexSet.IsFaceOf.iff_le_of_isFaceOf hxExtS hFface).mpr
      (Set.singleton_subset_iff.mpr hxF)
  set G : Finset P := insert (x : P) E_F with hGdef
  have hGsub : (G : Set P) ⊆ F := by
    rw [hGdef, Finset.coe_insert]
    exact Set.insert_subset hxF hE_Fsub
  have hGeq : F = Convexity.convexHull k (G : Set P) := by
    have hxmemhull : (x : P) ∈ Convexity.convexHull k (E_F : Set P) := hE_Feq ▸ hxF
    have habs : ({(x : P)} : Set P) ∪ Convexity.convexHull k (E_F : Set P) =
        Convexity.convexHull k (E_F : Set P) :=
      Set.union_eq_self_of_subset_left (Set.singleton_subset_iff.mpr hxmemhull)
    have h1 : Convexity.convexHull k (({(x : P)} : Set P) ∪ (E_F : Set P)) =
        Convexity.convexHull k (E_F : Set P) := by
      rw [← Convexity.convexHull_union_convexHull, habs]
      exact Convexity.IsConvexSet.convexHull_eq_self Convexity.IsConvexSet.convexHull
    rw [hGdef, Finset.coe_insert, ← Set.singleton_union, h1, hE_Feq]
  have hGext : ∀ z ∈ G, ({z} : Convexity.ConvexSet k P).IsFaceOf Fs := by
    intro z hz
    rw [hGdef, Finset.mem_insert] at hz
    rcases hz with rfl | hz
    · exact hxExtF
    · exact hE_Fext z hz
  -- `F` lies on the line through `x` in direction `v` (Lemma B), so its extreme points colinear
  -- with `x` along that line number at most two (Lemma C).
  have hFspan : F ⊆ affineSpan k ({(x : P), v +ᵥ (x : P)} : Set P) :=
    subset_affineSpan_pair_of_tangentCone_eq_ray k x' hcone_eq.symm
  have hGcard : G.card ≤ 2 :=
    card_le_two_of_forall_isFaceOf_of_subset_affineSpan_pair k hGsub (hGsub.trans hFspan) hGext
  have hxG : (x : P) ∈ G := Finset.mem_insert_self _ _
  -- `G` cannot be just `{x}`: that would force the tangent cone of `F` at `x` to be trivial,
  -- contradicting `v ≠ 0`.
  have hGne1 : G.card ≠ 1 := by
    intro hcard1
    obtain ⟨a, ha⟩ := Finset.card_eq_one.mp hcard1
    have hax : a = (x : P) := by rw [ha, Finset.mem_singleton] at hxG; exact hxG.symm
    have hFsingle : F = {(x : P)} := by rw [hGeq, ha, hax]; simp
    have hTeq : tangentCone k F x' = ⊥ := by
      have heq : tangentCone k F x' = PointedCone.hull k ((· -ᵥ (x : P)) '' F) :=
        tangentCone_eq_hull_image k F x'
      rw [heq, hFsingle]; simp
    exact hv0 (by
      have hvmem : (v : V) ∈ (k ∙₊ v : PointedCone k V) := PointedCone.subset_hull rfl
      rw [hcone_eq, hTeq] at hvmem
      exact hvmem)
  have hGcard2 : G.card = 2 := by
    have h1 : 1 ≤ G.card := Finset.one_le_card.mpr ⟨_, hxG⟩
    omega
  have hexists_ne : ∃ z ∈ G, z ≠ (x : P) := by
    by_contra hcon
    push_neg at hcon
    have hsub : G ⊆ {(x : P)} := fun z hz => Finset.mem_singleton.mpr (hcon z hz)
    have : G.card ≤ 1 := (Finset.card_le_card hsub).trans (by simp)
    omega
  obtain ⟨zmax, hzmaxG, hzmaxne⟩ := hexists_ne
  have hxzsub : ({(x : P), zmax} : Finset P) ⊆ G := by
    intro z hz
    simp only [Finset.mem_insert, Finset.mem_singleton] at hz
    rcases hz with rfl | rfl
    exacts [hxG, hzmaxG]
  have hxzcard : ({(x : P), zmax} : Finset P).card = 2 := Finset.card_pair hzmaxne.symm
  have hGeq2 : G = ({(x : P), zmax} : Finset P) :=
    (Finset.eq_of_subset_of_card_le hxzsub (by rw [hGcard2, hxzcard])).symm
  have hzmaxF : zmax ∈ F := hGsub hzmaxG
  have hzmaxmem : zmax -ᵥ (x : P) ∈ (k ∙₊ v : PointedCone k V) :=
    hcone_eq ▸ vsub_mem_tangentCone k F x' hzmaxF
  obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp hzmaxmem
  have hc0 : 0 < (c : k) := by
    rcases lt_or_eq_of_le c.2 with h | h
    · exact h
    · exfalso
      apply hzmaxne
      have hcz : c • v = (0 : V) := by
        rw [show c = (0 : {c : k // 0 ≤ c}) from Subtype.ext h.symm]; simp
      rw [hcz] at hc
      have h1 := congrArg (· +ᵥ (x : P)) hc.symm
      simpa using h1
  refine ⟨zmax, hzmaxF.1, ?_, (c : k), hc0, hc.symm, ?_⟩
  · have hzmax_mem_EF : zmax ∈ E_F := by
      have hzmax_mem_G : zmax ∈ G := hzmaxG
      rw [hGdef, Finset.mem_insert] at hzmax_mem_G
      exact hzmax_mem_G.resolve_left hzmaxne
    exact (hE_Fext zmax hzmax_mem_EF).trans hFface
  · have hFeq2 : F = Convexity.convexHull k ({(x : P), zmax} : Set P) := by
      rw [hGeq, hGeq2]; simp
    change (Convexity.ConvexSet.convexHull k ({(x : P), zmax} : Set P)).IsFaceOf _
    have hFseq : (Convexity.ConvexSet.convexHull k ({(x : P), zmax} : Set P)) = Fs := by
      apply SetLike.coe_injective
      change Convexity.convexHull k ({(x : P), zmax} : Set P) = F
      exact hFeq2.symm
    rw [hFseq]
    exact hFface

/-- The main theorem: the tangent cone at a vertex of a polytope is generated by finitely many
edge vectors — combining `IsPolytope.tangentCone_eq_hull_rays` (the tangent cone is the hull of
finitely many of its own ray faces) with `IsPolytope.exists_edge_of_ray_isFaceOf` (each such ray
is the direction of a genuine edge of `s`). -/
theorem IsPolytope.tangentCone_eq_hull_edgeVectors (hs : IsPolytope k s)
    (hx : IsExtremePoint k s (x : P)) :
    ∃ r : Finset V, PointedCone.hull k (r : Set V) = tangentCone k s x ∧
      ∀ v ∈ r, v ≠ 0 → ∃ y ∈ s, ({y} : Convexity.ConvexSet k P).IsFaceOf ⟨s, hs.isConvexSet⟩ ∧
        ∃ c : k, 0 < c ∧ y -ᵥ (x : P) = c • v ∧
          (Convexity.ConvexSet.convexHull k ({(x : P), y} : Set P)).IsFaceOf
            ⟨s, hs.isConvexSet⟩ := by
  obtain ⟨r, hr, hface⟩ := IsPolytope.tangentCone_eq_hull_rays k x hs hx
  exact ⟨r, hr, fun v hv hv0 =>
    IsPolytope.exists_edge_of_ray_isFaceOf k x hs hx hv0 (hface v hv)⟩

end Polytope

end Affine
